version: "3.7"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db_app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5431:5432"